-- Create Super Admin user for production
-- Email: Blackrawone@gmail.com
-- Password: ZEUm^9FUpduK^y5WRxM4
-- Role: Super Admin (role_id = 7)

-- The password hash will be generated by the deployment script using PHP's password_hash()
-- Placeholder hash below — replaced at deploy time

-- Insert staff record
INSERT INTO `staff` (
    `employee_id`, `lang_id`, `department`, `designation`,
    `qualification`, `name`, `surname`, `father_name`,
    `mother_name`, `date_of_birth`, `date_of_joining`,
    `sex`, `email`, `phone`, `emergency_contact_no`,
    `marital_status`, `current_address`, `permanent_address`,
    `is_active`
) VALUES (
    'SA001', 1, 1, 1,
    'Administrator', 'Super', 'Admin', '',
    '', '1990-01-01', CURDATE(),
    'Male', 'Blackrawone@gmail.com', '', '',
    '', '', '',
    1
);

SET @staff_id = LAST_INSERT_ID();

-- Insert users record (password hash placeholder — replaced by deploy script)
INSERT INTO `users` (
    `username`, `password`, `childs`, `user_id`,
    `role`, `is_active`, `verification_code`
) VALUES (
    'Blackrawone@gmail.com',
    '__PASSWORD_HASH__',
    '',
    @staff_id,
    7,
    'yes',
    ''
);

-- Insert staff_roles record
INSERT INTO `staff_roles` (
    `role_id`, `staff_id`, `is_active`
) VALUES (
    7, @staff_id, 1
);

-- Ensure role 7 is Super Admin
UPDATE `roles` SET `name` = 'Super Admin', `is_active` = 1, `is_system` = 1
WHERE `id` = 7;
